version: "3.8"
services:
  postgres:
    image: 'ankane/pgvector:v0.5.0'
    restart: always
    environment:
      - 'POSTGRES_DB=vector_ia'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256'
      - 'PGDATA: /var/lib/postgresql/data/pgdata'
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    ports:
      - '5442:5432'
    expose:
      - '5442'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vector_ia"]
      interval: 2s
      timeout: 20s
      retries: 5
      start_period: 10s
  pgadmin:
    container_name: pgadmin-container
    image: 'dpage/pgadmin4'
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=innovative@gmail.com'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    volumes:
      - './servers.json:/pgadmin4/servers.json'
    ports:
      - '5050:80'
#  innovativememory:
#    build:  .
#    container_name: innovativeMemory
#    ports:
#      - '8080:8080'
#    expose:
#      - '8080'
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
#      interval: 10s
#    depends_on:
#      postgres:
#        condition: service_healthy